add_newline = false

"$schema" = 'https://starship.rs/config-schema.json'

format = "$username $directory$character "

[character]
format = '$symbol \$'
success_symbol = '\[::\]'
error_symbol = '\[::\]'
vimcmd_symbol = '[\[::\]](bold red)'

[username]
format = '[$user]($style)'
show_always = true
