# VARIABLES
export EDITOR=nvim

# PATH
prepend_path() {
  if [ -d "$1" ]; then
    export PATH="$1:$PATH"
  fi
}

prepend_path $HOME/.local/bin
prepend_path $HOME/.cargo/bin
prepend_path $HOME/.pyenv/bin
prepend_path $HOME/bin

# Use for dotfiles that aren't managed by dot
try_source() {
    [ ! -s $1 ] || source $1
}

# SOURCES
source $HOME/.aliases
source $ZSH/oh-my-zsh.sh
try_source $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh

if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
fi

# OPTIONS
unsetopt AUTO_CD
setopt NO_BEEP
setopt RM_STAR_WAIT

bindkey -v
export KEYTIMEOUT=1

export GPG_TTY=$(tty)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use

# EVALS
eval "$(gh completion -s zsh)"
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
