# VARIABLES
export GOPATH=$HOME/go
export ZSH=$HOME/.oh-my-zsh
export TERM=xterm-256color
export EDITOR=vim
# export ZSH_THEME=spaceship
export ZEPHYR_BASE=~/zephyr/zephyr
export ALACRITTYRC=~/.config/alacritty/alacritty.yml
export VIMRC=~/.config/nvim/init.lua

# PLUGINS
plugins=(
  git
  # spaceship-vi-mode
)

fpath[1,0]=~/.zsh/completion/
fpath+=(~/.zsh/completion/_bazel)
fpath+=~/.zfunc

# PATH
prepend_path() {
  if [ -d "$1" ]; then
    export PATH="$1:$PATH"
  fi
}

prepend_path $HOME/.local/bin
prepend_path $HOME/.cargo/bin
prepend_path $HOME/.pyenv/bin
prepend_path $HOME/bin
prepend_path $HOME/.npm-global/bin
prepend_path /usr/local/texlive/2021/bin/x86_64-linux

# Use for dotfiles that aren't managed by dot
try_source() {
    [ ! -s $1 ] || source $1
}

# SOURCES
try_source $ZSH/oh-my-zsh.sh
source $HOME/.aliases
try_source $HOME/.oemrc

# OPTIONS
unsetopt AUTO_CD
setopt NO_BEEP
setopt RM_STAR_WAIT

# EVALS
eval "$(gh completion -s zsh)"
eval "$(zoxide init zsh)"
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
# eval "$(rbenv init -)"

bindkey -v
export KEYTIMEOUT=1

zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
export GPG_TTY=$(tty)

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use

# source $HOME/.spaceship
eval "$(starship init zsh)"
# krabby random 1-3

export PATH=$PATH:/home/jack/.spicetify

try_source $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh
